<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ABMLMedicos1.aspx.cs" Inherits="Vistas.ABMLMedicos1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 165px;
        }
        .auto-style3 {
            width: 165px;
            height: 23px;
        }
        .auto-style4 {
            height: 23px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table class="auto-style1">
                <tr>
                    <td class="auto-style2">
                        <asp:Label ID="Lbl_GrillaMedicos" runat="server" Text="GRILLA MEDICOS"></asp:Label>
                    </td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">
            <asp:Label ID="Lbl_NombreAdministrador" runat="server"></asp:Label>
                    </td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>
                        <asp:GridView ID="GrdMedicos" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateEditButton="True" OnRowEditing="GrdMedicos_RowEditing" OnRowUpdating="GrdMedicos_RowUpdating" AutoGenerateDeleteButton="True" OnRowDataBound="GrdMedicos_RowDataBound" OnRowDeleting="GrdMedicos_RowDeleting" OnRowCancelingEdit="GrdMedicos_RowCancelingEdit">
                            <Columns>
                                <asp:TemplateField HeaderText="Legajo_Med">
                                    <EditItemTemplate>
                                        <asp:Label ID="Lbl_eit_Legajo_Med" runat="server" Text='<%# Bind("Legajo_Med") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Lbl_it_Legajo" runat="server" Text='<%# Bind("Legajo_Med") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="DNI_Med">
                                    <EditItemTemplate>
                                        <asp:Label ID="Lbl_eit_Dni_Med" runat="server" Text='<%# Bind("DNI_Med") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Lbl_it_Dni" runat="server" Text='<%# Bind("DNI_Med") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Nombre_Med">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="Txt_eit_Nombre_Med" runat="server" Text='<%# Bind("Nombre_Med") %>'></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="Rfv_Txt_eit_Nombre_Med" runat="server" ControlToValidate="Txt_eit_Nombre_Med" Display="Dynamic">*</asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Lbl_it_Nombre" runat="server" Text='<%# Bind("Nombre_Med") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                                            <asp:TemplateField HeaderText="APELLIDO MEDICO">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Apellido_Med" runat="server" Text='<%# Bind("Apellido_Med") %>'></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="Rfv_Txt_eit_Apellido_Med" runat="server" ControlToValidate="Txt_eit_Apellido_Med" Display="Dynamic">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_ApellidoMedico" runat="server" Text='<%# Bind("Apellido_Med") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="SEXO MEDICO">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="Ddl_eit_Sexo_Med" runat="server">
                                        <asp:ListItem>-- Sexo --</asp:ListItem>
                                        <asp:ListItem>F</asp:ListItem>
                                        <asp:ListItem>M</asp:ListItem>
                                    </asp:DropDownList>
                                    <asp:RequiredFieldValidator ID="Rfv_Ddl_eit_Sexo_Med" runat="server" ControlToValidate="Ddl_eit_Sexo_Med" InitialValue="-- Sexo --" Display="Dynamic">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_SexoMedico" runat="server" Text='<%# Bind("Sexo_Med") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Nacionalidad">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Nacionalidad_Med" runat="server" Text='<%# Bind("Nacionalidad_Med") %>'></asp:TextBox>
                                    &nbsp;<asp:RequiredFieldValidator ID="Rfv_Txt_eit_Nacionalidad_Med" runat="server" ControlToValidate="Txt_eit_Nacionalidad_Med" Display="Dynamic">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Nacionalidad" runat="server" Text='<%# Bind("Nacionalidad_Med") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Fecha Nacimiento">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_FechaNacimientoMed" runat="server" Text='<%# Bind("Fecha_Nacimiento_Med") %>'></asp:TextBox>
                                    &nbsp;
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_FechaNacimiento" runat="server" Text='<%# Bind("Fecha_Nacimiento_Med") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Direccion">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Direccion_Med" runat="server" Text='<%# Bind("Direccion") %>'></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="Rfv_Txt_eit_Direccion_Med" runat="server" ControlToValidate="Txt_eit_Direccion_Med">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Direccion" runat="server" Text='<%# Bind("Direccion") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Localidad">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="Ddl_eit_Nombre_Loc" runat="server">
                                    </asp:DropDownList>
                                    &nbsp;<asp:RequiredFieldValidator ID="Rfv_Ddl_eit_Nombre_Loc" runat="server" ControlToValidate="Ddl_eit_Nombre_Loc">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Localidad" runat="server" Text='<%# Bind("Nombre_Loc") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provincia">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="Ddl_eit_Provincia" runat="server" AutoPostBack="True" OnSelectedIndexChanged="Ddl_eit_Provincia_SelectedIndexChanged1">
                                    </asp:DropDownList>
                                    &nbsp;<asp:RequiredFieldValidator ID="Rfv_Ddl_eit_Provincia" runat="server" ControlToValidate="Ddl_eit_Provincia">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Provincia" runat="server" Text='<%# Bind("Nombre_Prov") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Correo">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Correo_Med" runat="server" Text='<%# Bind("Correo_Med") %>'></asp:TextBox>
                                    &nbsp;<asp:RegularExpressionValidator ID="Rfv_Txt_eit_Correo_Med" runat="server" ControlToValidate="Txt_eit_Correo_Med" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*">*</asp:RegularExpressionValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Correo_Med" runat="server" Text='<%# Bind("Correo_Med") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Telefono">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Telefono_Med" runat="server" Text='<%# Bind("Telefono_Med") %>'></asp:TextBox>
                                    &nbsp;<asp:RegularExpressionValidator ID="Rev_Txt_eit_Telefono_Med" runat="server" ControlToValidate="Txt_eit_Telefono_Med" Display="Dynamic" ValidationExpression="^\d{8}$" ValidationGroup="EditarMedico">*</asp:RegularExpressionValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Telefono_Med" runat="server" Text='<%# Bind("Telefono_Med") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Especialidad">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="Ddl_eit_especialidad" runat="server">
                                    </asp:DropDownList>
                                    &nbsp;<asp:RequiredFieldValidator ID="Rfv_Ddl_eit_especialidad" runat="server" ControlToValidate="Ddl_eit_especialidad" Display="Dynamic" ValidationGroup="EditarMedico">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_EspecialidadMedico" runat="server" Text='<%# Bind("Nombre_Especialidad") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>

                            </Columns>
                        </asp:GridView>
                    </td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">
                    <asp:Label ID="LblMedico" runat="server"></asp:Label>
                    </td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">
                    <asp:HyperLink ID="hlABMLMedicos" runat="server" NavigateUrl="Administrador.aspx">&lt;- Volver</asp:HyperLink>
                    </td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3"></td>
                    <td class="auto-style4"></td>
                    <td class="auto-style4"></td>
                    <td class="auto-style4"></td>
                    <td class="auto-style4"></td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
