<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ABMLPacientes.aspx.cs" Inherits="Vistas.ABMLPacientes" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 138px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="LblNombreUsuario" runat="server"></asp:Label>
            <br />
            GRILLA DE PACIENTES</div>
        <table class="auto-style1">
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td>
                    <asp:TextBox ID="txtFiltrarNombre" runat="server"></asp:TextBox>
&nbsp;<asp:Button ID="BtnFiltrarNombre" runat="server" Text="Filtrar nombre" OnClick="BtnFiltrarNombre_Click" />
                &nbsp;
                    <asp:Button ID="btnMostrarTodos" runat="server" OnClick="btnMostrarTodos_Click" Text="Mostrar Todos" />
                </td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td>
                    <asp:GridView ID="GrdPacientes" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="GrdPacientes_RowDeleting" OnRowEditing="GrdPacientes_RowEditing" OnSelectedIndexChanging="GrdPacientes_SelectedIndexChanging" OnRowCancelingEdit="GrdPacientes_RowCancelingEdit" OnRowUpdating="GrdPacientes_RowUpdating" AllowPaging="True" OnRowDataBound="GrdPacientes_RowDataBound">
                        <Columns>
                            <asp:TemplateField HeaderText="DNI">
                                <EditItemTemplate>
                                    <asp:Label ID="Lbl_eit_DNI_Pa" runat="server" Text='<%# Bind("DNI_Pa") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_DniPaciente" runat="server" Text='<%# Bind("DNI_Pa") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="NOMBRE">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Nombre_Pa" runat="server" Text='<%# Bind("Nombre_Pa") %>'></asp:TextBox>
                                    <%--<asp:RegularExpressionValidator ID="revNombre" runat="server" ControlToValidate="Txt_eit_Nombre_Pa" ErrorMessage="Nombre inválido" ValidationExpression="^[a-zA-Z]{1,20}$" Display="Dynamic"></asp:RegularExpressionValidator>--%>
                                    <asp:RegularExpressionValidator ID="RevNombre" runat="server" ControlToValidate="Txt_eit_Nombre_Pa" ErrorMessage="Nombre no valido" ValidationExpression="^[a-zA-Z]{1,20}$" Display="Dynamic"></asp:RegularExpressionValidator>
                                    &nbsp;<asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="Txt_eit_Nombre_Pa" Display="Dynamic">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Nombre" runat="server" Text='<%# Bind("Nombre_Pa") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="APELLIDO">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Apellido_Pa" runat="server" Text='<%# Bind("Apellido_Pa") %>'></asp:TextBox>
                                    <asp:RegularExpressionValidator ID="RevApellido" runat="server" ControlToValidate="Txt_eit_Apellido_Pa" Display="Dynamic" ErrorMessage="Apellido invalido" ValidationExpression="^[a-zA-Z]{1,20}$"></asp:RegularExpressionValidator>
                                    &nbsp;<asp:RequiredFieldValidator ID="Rfv_Txt_Apellido" runat="server" ControlToValidate="Txt_eit_Apellido_Pa" Display="Dynamic">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Apellido" runat="server" Text='<%# Bind("Apellido_Pa") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="SEXO">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="Ddl_eit_Sexo" runat="server">
                                        <asp:ListItem>-- Selecionar Sexo --</asp:ListItem>
                                        <asp:ListItem>F</asp:ListItem>
                                        <asp:ListItem>M</asp:ListItem>
                                    </asp:DropDownList>
                                    <asp:RequiredFieldValidator ID="Rfv_Sexo" runat="server" ControlToValidate="Ddl_eit_Sexo" Display="Dynamic" InitialValue="-- Selecionar Sexo --">Seleccionar</asp:RequiredFieldValidator>
                                    &nbsp;<asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="Ddl_eit_Sexo" Display="Dynamic" InitialValue="-- Selecionar Sexo --">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Sexo" runat="server" Text='<%# Bind("Sexo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="NACIONALIDAD">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Nacionalidad_Pa" runat="server" Text='<%# Bind("Nacionalidad_Pa") %>'></asp:TextBox>
                                    &nbsp;<asp:RequiredFieldValidator ID="Rfv_Txt_Nacionalidad" runat="server" ControlToValidate="Txt_eit_Nacionalidad_Pa">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Nacionalidad" runat="server" Text='<%# Bind("Nacionalidad_Pa") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="FECHA NACIMIENTO">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Fecha_Nacimiento_Pa" runat="server" Text='<%# Bind("Fecha_Nacimiento_Pa") %>'></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="Rfv_Txt_Fecha" runat="server" ControlToValidate="Txt_eit_Fecha_Nacimiento_Pa" Display="Dynamic">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_FechaNacimiento" runat="server" Text='<%# Bind("Fecha_Nacimiento_Pa") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="DIRECCION">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Direccion_Pa" runat="server" Text='<%# Bind("Direccion_Pa") %>'></asp:TextBox>
                                    &nbsp;<asp:RequiredFieldValidator ID="Rfv_Txt_Direccion" runat="server" ControlToValidate="Txt_eit_Direccion_Pa" Display="Dynamic">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Direccion" runat="server" Text='<%# Bind("Direccion_Pa") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="ID LOCALIDAD">
                                <EditItemTemplate>
                                    <asp:Label ID="Lbl_eit_Id_Localidad" runat="server" Text='<%# Bind("Id_Localidad") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lbl_it_Id_Localidad" runat="server" Text='<%# Bind("Id_Localidad") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Localidad">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="Ddl_eit_Nombre_Loc" runat="server" AutoPostBack="True" OnSelectedIndexChanged="Ddl_eit_Nombre_Loc_SelectedIndexChanged">
                                    </asp:DropDownList>
                                    <asp:RequiredFieldValidator ID="RfvLocalidad" runat="server" ControlToValidate="Ddl_eit_Nombre_Loc" Display="Dynamic" InitialValue="Seleccione Localidad">Seleccione Localidad</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_eit_NombreLoc" runat="server" Text='<%# Bind("Nombre_Loc") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provincia">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="Ddl_eit_Provincia" runat="server" OnSelectedIndexChanged="Ddl_eit_Provincia_SelectedIndexChanged" AutoPostBack="True">
                                    </asp:DropDownList>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Provincia" runat="server" Text='<%# Bind("Nombre_Prov") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="CORREO">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Correo_Pa" runat="server" Text='<%# Bind("Correo_Pa") %>'></asp:TextBox>
                                    <asp:RegularExpressionValidator ID="RevCorreo" runat="server" ControlToValidate="Txt_eit_Correo_Pa" Display="Dynamic" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*">Correo Invalido</asp:RegularExpressionValidator>
                                    &nbsp;<asp:RequiredFieldValidator ID="Rfv_Txt_Correo" runat="server" ControlToValidate="Txt_eit_Correo_Pa" Display="Dynamic">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Correo_Pa" runat="server" Text='<%# Bind("Correo_Pa") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="TELEFONO">
                                <EditItemTemplate>
                                    <asp:TextBox ID="Txt_eit_Telefono_Pa" runat="server" Text='<%# Bind("Telefono_Pa") %>'></asp:TextBox>
                                    <asp:RegularExpressionValidator ID="RevTelefono" runat="server" ControlToValidate="Txt_eit_Telefono_Pa" Display="Dynamic" ValidationExpression="^\d{8}$" ValidationGroup="AgregarPaciente">Numero Invalido</asp:RegularExpressionValidator>
                                    &nbsp;<asp:RequiredFieldValidator ID="Rfv_Txt_Telefono" runat="server" ControlToValidate="Txt_eit_Telefono_Pa">*</asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Telefono_Pa" runat="server" Text='<%# Bind("Telefono_Pa") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="ESTADO">
                                <EditItemTemplate>
                                    <asp:Label ID="LblEstado" runat="server" Text='<%# Bind("Estado") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Lbl_it_Estado" runat="server" Text='<%# Bind("Estado") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td>
                    <asp:Label ID="LblPaciente" runat="server"></asp:Label>
                &nbsp;</td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <asp:HyperLink ID="hlABMLPacientes" runat="server" NavigateUrl="Administrador.aspx">&lt;- Volver</asp:HyperLink>
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
